# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 22:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import transacciones.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Localizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia_fecha_desde', models.DateField()),
                ('vigencia_fecha_hasta', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='localizacion',
            name='localizacion_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transacciones.Localizacion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='dummy',
            field=models.CharField(default='---', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='numero_consecutivo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='logo',
            field=models.FileField(max_length=500, upload_to=transacciones.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='nombre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='consecutivo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion_bien_servicio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='es_secreto',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_requerido',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_terminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='localizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transacciones.Localizacion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transacciones.Moneda'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nivel_inteligencia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='numero_contrato_marco',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='numero_orden_compra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='numero_pedido_ot_od_os',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='numero_proceso',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='numero_requerimiento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='objeto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedores_sugeridos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transacciones.TipoContrato'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_contrato_cual',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transacciones.TipoUbicacion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tipocontrato',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tipoobjeto',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tipoubicacion',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='usuario_localizacion',
            name='localizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transacciones.Localizacion'),
        ),
        migrations.AddField(
            model_name='usuario_localizacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transacciones.TipoProducto'),
        ),
    ]
