# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-10 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_auto_20160509_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='dummy',
            field=models.CharField(max_length=50),
        ),
    ]
