# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-10 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0004_auto_20160509_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='detalles',
            field=models.CharField(default='----', max_length=50),
            preserve_default=False,
        ),
    ]
