# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 18:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import transacciones.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transacciones', '0005_producto_detalles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo_Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo', models.FileField(upload_to=transacciones.models.content_file_name_anexo)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=500)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transacciones.Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=100)),
                ('estado_actual', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=500)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transacciones.Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
