# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0005_auto_20160422_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='localizacion',
            name='nombre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion_bien_servicio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_terminacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='objeto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='observaciones',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedores_sugeridos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tipocontrato',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tipoobjeto',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tipoubicacion',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
