# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0006_anexo_producto_estado_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='detalles',
        ),
        migrations.AlterField(
            model_name='anexo_producto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transacciones.Producto'),
        ),
        migrations.AlterField(
            model_name='estado_producto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transacciones.Producto'),
        ),
    ]
