# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-27 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0007_producto_numero_consecutivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='transacciones.TipoProducto'),
            preserve_default=False,
        ),
    ]
