# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-27 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0010_auto_20160427_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
