# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import transacciones.models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0011_auto_20160427_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='logo',
            field=models.FileField(max_length=500, upload_to=transacciones.models.content_file_name),
        ),
    ]
